### ISSUE TITLE
Deploying to Cloudflare Pages/Workers

### ISSUE THREAD

**Issue by leebeydoun** [firebolt-dev/firebolt#2]
Hello, I didn’t see a discussion section in the repo, but I’m quite interested in using Firebolt.

Essentially I like the simplicity of it but understandably things still seem quite bare. 

Is there a guide or approach I can look at to deploy a firebolt app using Cloudflare?

**Comment by ashconnell** [comment]
Right now you can deploy anywhere that supports Node.js such as Fly, Render, Heroku or any custom server. 

Some work has already been done to eventually support other runtimes like Cloudflare Workers
