### ISSUE TITLE
Feature Request: Support JSX file

### ISSUE THREAD

**Issue by jellydn** [firebolt-dev/firebolt#3]
# Why

That's a common pattern that people would use `.jsx` for React components.

# What

Support JSX filename

# Possible solution 

Instead of load `.js` on firebolt lib, we could search for `.js*`.

# Reproduce:
 - Try to change _layout.js to _layout.jsx 

```js

> firebolt-grit-demo@0.3.1 dev
> firebolt dev


  🔥 Firebolt (v0.3.1)

 INF  building...
 ERR  BuildError: Could not resolve "../routes/_layout.js"

    .firebolt/lib.js:15:21:
    15 | import Document from '../routes/_layout.js'
       |                      ~~~~~~~~~~~~~~~~~~~~~~

 CHN  ~/.git/FETCH_HEAD
 INF  building...
 ERR  BuildError: Could not resolve "../routes/_layout.js"

    .firebolt/lib.js:15:21:
    15 | import Document from '../routes/_layout.js'
       |                      ~~~~~~~~~~~~~~~~~~~~~~

```

**Comment by ashconnell** [comment]
You only need to name your files `.js` because the JSX is automatically implied, since this is a React framework. 

What benefit do you get from naming them `.jsx`?

**Comment by jellydn** [comment]
I guess you want to make it simple however you would want to support linter, e.g ESLint rule https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-filename-extension.md

Or support Biome
<img width="1391" alt="image" src="https://github.com/firebolt-dev/firebolt/assets/870029/228f8ffd-c37c-45a1-ba23-e1f43886f35e">

Works fine with `.jsx` filename 
<img width="1445" alt="image" src="https://github.com/firebolt-dev/firebolt/assets/870029/5016ba74-4a2f-4fae-8c99-28bea2d25421">

**Comment by ashconnell** [comment]
That’s fair. I should be able to add optional support for using that as an extension, at least for those who want it.
